spring:
    datasource:
        url: jdbc:mysql://localhost:3306/shopping?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
        password: wkd13656559069
        username: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    mvc:
    static-path-pattern: /**
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/,classpath:/public/,classpath:/itstyle/

mybatis-plus:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
    type-aliases-package: com.shopping.entity
    mapper-locations: classpath*:mappers/*.xml
server:
    port: 8989
